### ISSUE TITLE
首次启动这里一直加载中, 不动了.

### ISSUE THREAD

**Issue by Dssssds** [licheng1013/admin-flutter#2]
cc3f894e Importing root project [Done]
1f30a8a0 Check JDK Index [Done]
8c1bb107 Building [Done]
8f95dc19 Building [Done]
8f83070d Building [Done]
48b30420 Importing root project - 50% Refreshing '/android'.

小白提问.感谢回答.

**Comment by licheng1013** [comment]
flutter doctor 看一下。 把启动的方式截图下。

**Comment by Dssssds** [comment]
flutter doctor 
![image](https://github.com/user-attachments/assets/37524602-99eb-4102-b6c2-bb22e161ab7b)

博主,这个是不是需要配置 android 呢?

**Comment by licheng1013** [comment]
开发阶段你选这个启动 
![image](https://github.com/user-attachments/assets/05227208-e91c-498c-9d3e-256b273e4bc7)

**Comment by Dssssds** [comment]
感谢感谢,可以了.我在学习 flutter ,在借鉴您的 admin 后台. 我有疑问会 发起 issues.
