### ISSUE TITLE
在线的演示地址界面的字体和本地代码Web调试的界面字体不一样

### ISSUE THREAD

**Issue by ismlsmile** [licheng1013/admin-flutter#3]
请问下是什么原因？
![无标题](https://github.com/user-attachments/assets/82e52f26-8abb-4a41-98b1-cffd2fb63f57)

**Comment by licheng1013** [comment]
试一下Windows启动的结果看下，如果也一样。可能是字体没有正确加载。否则就是web调试渲染的问题 (可能换字体有效)

**Comment by ismlsmile** [comment]
windows平台字体是ok的，确实是雅黑。但在web下字体不是雅黑。我看代码只有在windows平台上才设置了雅黑，所以理论上web下字体不是雅黑是正常的，不知道为什么你部署出来的在线demo字体是雅黑的

**Comment by licheng1013** [comment]
可能调试时浏览器跟正常浏览器有差异吧。

**Comment by ismlsmile** [comment]
请问你发布web的时候命令用的是flutter build web吗？有没有加其它参数

**Comment by licheng1013** [comment]
flutter build web --web-renderer html --base-href /admin-flutter/   我用的 html 渲染方式，如果是根路径就不需要 --base-href /admin-flutter/

**Comment by ismlsmile** [comment]
试了下，就是这个原因，默认渲染方式是canvaskit，这种模式下字体有问题，用html就和在线演示环境一致了
